# Choose an optional name for the datacenter
global:
  datacenter: middleware

# Enable the Consul Web UI via a NodePort
ui:
  service:
    type: NodePort

# Enable Connect for secure communication between nodes
connectInject:
  enabled: true

client:
  enabled: true
  extraConfig: |
    {
      "watches": [
        {
          "type": "services",
          "handler_type": "http",
          "http_handler_config": {
            "path": "http://reactor.default/service",
            "method": "POST",
            "timeout": "3s",
            "tls_skip_verify": false
          }
        }
      ]
    }

# Use only one Consul server for local development
server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0

syncCatalog:
  enabled: true
